export const NewData = {
  multipleProjects: [
    {
      title: "Create Your OWN Artificial Intelligence Platform Using ML/DL & Generative AI Integrated With DevOps Pipeline Along With Cloud Computing - Generative AIOps",
      description: "Develop Own Cloud Computing with AI Intelligence by Custom Machine/Deep Learning Model that deploy using DevOps Technology Integrated with Generative AI - ChatGPT API",
      image: {
        src: "/assets/Projects/106.gif",
        alt: "Generative AIOps Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
        "Numpy",
        "Pandas",
        "Matplotlib",
        "Seaborn",
        "TensorFlow",
        "Pytorch",
        "Keras",
        "Model tuning and performance analytics",
        "Data preprocessing",
        "Data Transformation",
        "Data Reduction",
        "Data Visualization",
        "Classification",
        "Exploratory Data Analysis",
        "Clustering",
        "Regression Models",
        "Neural Network",
        "Simple Neural Networks",
        "Advance Neural Network",
        "CNN (Convolutional Neural Network)",
        "RNN (Recurrent Neural Network)",
        "GAN (Generative Adversarial Network)",
        "LSTM (Long Short-Term Memory)",
        "Filtering Methods",
        "RBM",
        "Advanced NN models",
        "Transfer Learning",
        "Reinforcement Learning",
        "Generative AI (ChatGPT, media, code, and simulations)",
        "Data Processing and Analytics",
        "NLP – Text Analytics",
        "Speech Analytics",
        "Association Mining",
        "Recommendation System",
        "AWS Cloud",
        "Amazon SageMaker",
        "Rekognition",
        "Comprehend",
        "Transcribe",
        "Amazon Forecast",
        "Personalize",
        "Lex",
        "Fraud Detector",
        "Translate",
        "Polly",
        "Pipeline as Code",
        "Docker",
        "Podman",
        "Kubernetes",
        "Openshift",
        "Terraform",
        "Jenkins",
        "RedHat Linux",
        "Virtualization (Web App)",
        "RestAPI",
        "Flutter OR React Native (Mobile App)",
        "Html",
        "CSS",
        "Javascript",
        "Django OR Flask OR Nodejs (Web App)",
        "Mysql",
        "MongoDB",
        "Git",
        "Github",
        "RHELv9 (Red Hat Enterprise Linux)"
      ],
      registerLink: "https://rzp.io/rzp/LcByPAT ",
      originalPrice: "",
      price: "15,000",
      projectCode: "LW-PSI-SP-106"
    }
  ],
  individualProjects: [
    {
      title: "1. MACHINE LEARNING - AI",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/MLAI.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
        "Data Science",
        "Keras",
        "Pandas",
        "Deep learning",
        "Reinforcement Learning",
        "Numpy",
        "Classification",
        "Clustering",
        "Supervised Learning",
        "Un Supervised Learning",
        "Feature Engineering",
        "CNN",
        "Traditional Machine Learning Techniques",
        "Computer Vision",
        "NLP",
        "Preprocessing Data",
        "Model Evaluation",
        "Neural Network",
        "Validation Techniques",
        "Hyperparameter Tuning",
        "Optimization",
      ],
      registerLink: "https://rzp.io/rzp/47kmYFCr",
      originalPrice: "",
      price: "8,000 ",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "2. AWS CLOUD COMPUTING",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/AWS.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "AWS CLI", "Snapshot",
        "AWS Global Network",
        "Storage",
        "EBS",
        "EFS(Elastic file system)",
        "API Gateway",
        "Cloud Watch",
        "Route 53",
        "Virtual Private Cloud",
        "AWS Serverless",
        "AWS Load Balancer Service",
        "Monitoring & Scaling",
        "Access Management",
        "AMI",
        "Networking",
        "Security & Automation",
        "Amazon Rekognition",
        "Introduction to AWS AI Services",
        "Amazon Comprehend",
        "Amazon Transcribe",
        "Amazon Translate",
        "Amazon Forecast"
      ],
      registerLink: "https://rzp.io/rzp/Og4HCEB ",
      originalPrice: "16,000",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "3. PYTHON PROGRAMMING",
      description: "Develop High-End Next Generation End to End DevOps Pipeline Managed Service in High Performance Cloud Computing Platform.",
      image: {
        src: "/assets/Projects/Projects/Python.png",
        alt: "DevOps Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Anaconda and Jupyter Notebook",
        "Variables and Data Types",
        "Running Python Programs",
        "Python Data Structures",
        "Arithmetic Operations and Operators",
        "Regular Expressions",
        "Conditionals & Loops",
        "Functions and Arguments",
        "Working with Files and Directories",
        "Python Modules and Packages",
        "Exception Handling",
        "Multi-Threading And Socket Programming",
        "Python Object-Oriented Programming"
      ],
      registerLink: "https://rzp.io/rzp/srRJcza  ",
      originalPrice: "",
      price: "8,000",
      projectCode: "LW-PSI-SP-101"
    },
    {
      title: "4. PYTHON FULL STACK WEB DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/PythoFullStack.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "Static Web Page",
        "Dynamic Web Page",
        "API",
        "GET & POST Method",
        "POSTMAN",
        "HTTPD Web Server",
        "HTML Form",
        "DOM",
        "DOM TREE",
        "TABLES",
        "JavaScript",
        "EVENTS",
        "Asynchronous Java Script",
        "Data Types in Java Script",
        "REGEX",
        "Loops",
        "Arrays",
        "React.js",
        "Bootstrap",
        "Python",
        "Git And GitHub",
        "Flask",
        "MySQL",
      ],
      registerLink: "https://rzp.io/rzp/6duw8S3W ",
      originalPrice: "",
      price: "8,000 ",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "5. MERN STACK DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/MERN.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "HTML",
        "CSS",
        "JavaScript",
        "MACHINE LEARNING-AI",
        "React JS",
        "Node JS",
        "Express JS",
        "MongoDB",
        "Hooks",
        "Document Object Model (DOM)",
        "Routing and APIs",
        "Asynchronous Programming",
        "Building RESTful APIs",
        "Fetching Data from API",
        "Handling Forms and User Input",
        "MERN STACK DEVELOPMENT",
        "Code Organization and Structure",
        "Error Handling"
      ],
      registerLink: "https://rzp.io/rzp/rbFeiL6",
      originalPrice: "",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },
    
    {
      title: "6. Salesforce Admin & Development",
      description: "Build and customize CRM applications using Salesforce by mastering administration, automation, data tools, and development with Apex and Lightning Web Components.",

      image: {
        src: "/assets/Projects/Salesforce.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
      "Overview of Salesforce",
      "Sales Cloud",
      "Salesforce Objects, Fields & formula fields",
      "Data Migration Tools",
      "Salesforce Security",
      "Automation in Salesforce",
      "Role Hierarchy",
      "Reports & DashBoard",
      "Apex programming",
      "DML",
      "SOQL and SOSL",
      "Apex Trigger",
      "Visualforce",
      "LWC"

      ],
      registerLink: "https://rzp.io/rzp/AgXliZXG ",
      originalPrice: "",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },

    {
      title: "7. Cybersecurity",
      description: "Learn to protect networks, systems, and data through ethical hacking, threat detection, and defense strategies using industry-standard cybersecurity tools and practices.",
      image: {
        src: "/assets/Projects/Cybersecurity.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Basic Networking Concepts",
        "Overview",
        "Overview of Cyber Law",
        "Computer Virtualization Tech & LAB Setup",
        "Information Gathering - Printing",
        "Windows, Linux Password Hacking & Security",
        "Other Concepts for Cyber Security",
        "Mobile Phone Hacking",
        "Denial of Service Attack - DOS Attack",
        "Proxy Server & Virtual Private Network",
        "Google Hacking & its Database",
        "Social Sites Hacking & Security Issues",
        "Email Hacking and Tracing",
        "Linux Training",
        "Wireless Hacking"
        
      ],
      registerLink: "https://rzp.io/rzp/zihXhnn ",
      originalPrice: "",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },

    {
      title: "8. Embedded systems, IOT, and Robotics",
      description: "Design smart systems using embedded hardware, IoT protocols, and robotics to automate real-world tasks through sensors, controllers, and wireless communication.",

      image: {
        src: "/assets/Projects/IOT.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "GPIO",
        "Liquid Crystal Display",
        "Keys/Switches",
        "Keypad Matrix",
        "PWM & Timer",
        "Motors",
        "Serial Communication",
        "Sensors - ADC, flame, flex, LDR, gas sensors…more",
        "Bluetooth & RF",
        "EEPROM",
        "IoT Platform & Communication",
        "MQTT",
        "IoT Web App – HTML, CSS, Flask, DB, Analytics, GCP, Public",
        "IoT Application",

        
      ],
      registerLink: "https://rzp.io/rzp/oyIPDq3l",
      originalPrice: "",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },


    
  ]
};