export const NewData = {
  multipleProjects: [
    {
      title: "Create Your OWN Artificial Intelligence Platform Using ML/DL & Generative AI Integrated With DevOps Pipeline Along With Cloud Computing - Generative AIOps",
      description: "Develop Own Cloud Computing with AI Intelligence by Custom Machine/Deep Learning Model that deploy using DevOps Technology Integrated with Generative AI - ChatGPT API",
      image: {
        src: "/assets/Projects/106.gif",
        alt: "Generative AIOps Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
        "Numpy",
        "Pandas",
        "Matplotlib",
        "Seaborn",
        "TensorFlow",
        "Pytorch",
        "Keras",
        "Model tuning and performance analytics",
        "Data preprocessing",
        "Data Transformation",
        "Data Reduction",
        "Data Visualization",
        "Classification",
        "Exploratory Data Analysis",
        "Clustering",
        "Regression Models",
        "Neural Network",
        "Simple Neural Networks",
        "Advance Neural Network",
        "CNN (Convolutional Neural Network)",
        "RNN (Recurrent Neural Network)",
        "GAN (Generative Adversarial Network)",
        "LSTM (Long Short-Term Memory)",
        "Filtering Methods",
        "RBM",
        "Advanced NN models",
        "Transfer Learning",
        "Reinforcement Learning",
        "Generative AI (ChatGPT, Data, Audio, Code, Images, Simulations)",
        "Data Processing and Analytics",
        "NLP – Text Analytics",
        "Speech Analytics",
        "Association Mining",
        "Recommendation System",
        "AWS Cloud",
        "Amazon SageMaker",
        "Rekognition",
        "Comprehend",
        "Transcribe",
        "Amazon Forecast",
        "Personalize",
        "Lex",
        "Fraud Detector",
        "Translate",
        "Polly",
        "Pipeline as Code",
        "Docker",
        "Podman",
        "Kubernetes",
        "Openshift",
        "Terraform",
        "Jenkins",
        "RedHat Linux",
        "Virtualization (Web App)",
        "RestAPI",
        "Flutter OR React Native (Mobile App)",
        "Html",
        "CSS",
        "Javascript",
        "Django OR Flask OR Nodejs (Web App)",
        "Mysql",
        "MongoDB",
        "Git",
        "Github",
        "RHELv9 (Red Hat Enterprise Linux)"
      ],
      registerLink: "https://rzp.io/r/zAIops",
      originalPrice: "30,000",
      price: "15,000",
      projectCode: "LW-PSI-SP-106"
    }
  ],
  individualProjects: [
    {
      title: "1. MACHINE LEARNING - AI",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/MLAI.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Python",
        "Data Science",
        "Keras",
        "Pandas",
        "Deep learning",
        "Reinforcement Learning",
        "Numpy",
        "Classification",
        "Clustering",
        "Supervised Learning",
        "Un Supervised Learning",
        "Feature Engineering",
        "CNN",
        "Traditional Machine Learning Techniques",
        "Computer Vision",
        "NLP",
        "Preprocessing Data",
        "Model Evaluation",
        "Neural Network",
        "Validation Techniques",
        "Hyperparameter Tuning",
        "Optimization",
      ],
      registerLink: "https://rzp.io/rzp/NV4dSzP",
      originalPrice: "16,000",
      price: "8,000 ",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "2. AWS CLOUD COMPUTING",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/AWS.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "AWS CLI", "Snapshot",
        "AWS Global Network",
        "Storage",
        "EBS",
        "EFS(Elastic file system)",
        "API Gateway",
        "Cloud Watch",
        "Route 53",
        "Virtual Private Cloud",
        "AWS Serverless",
        "AWS Load Balancer Service",
        "Monitoring & Scaling",
        "Access Management",
        "AMI",
        "Networking",
        "Security & Automation",
        "Amazon Rekognition",
        "Introduction to AWS AI Services",
        "Amazon Comprehend",
        "Amazon Transcribe",
        "Amazon Translate",
        "Amazon Forecast"
      ],
      registerLink: "https://rzp.io/rzp/tN0AHIT",
      originalPrice: "16,000",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "3. PYTHON PROGRAMMING",
      description: "Develop High-End Next Generation End to End DevOps Pipeline Managed Service in High Performance Cloud Computing Platform.",
      image: {
        src: "/assets/Projects/Projects/Python.png",
        alt: "DevOps Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Anaconda and Jupyter Notebook",
        "Variables and Data Types",
        "Running Python Programs",
        "Python Data Structures",
        "Arithmetic Operations and Operators",
        "Regular Expressions",
        "Conditionals & Loops",
        "Functions and Arguments",
        "Working with Files and Directories",
        "Python Modules and Packages",
        "Exception Handling",
        "Multi-Threading And Socket Programming",
        "Python Object-Oriented Programming"
      ],
      registerLink: "https://rzp.io/rzp/OHIOmeR ",
      originalPrice: "8,000",
      price: "16,000",
      projectCode: "LW-PSI-SP-101"
    },
    {
      title: "4. PYTHON FULL STACK WEB DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/PythoFullStack.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "Static Web Page",
        "Dynamic Web Page",
        "API",
        "GET & POST Method",
        "POSTMAN",
        "HTTPD Web Server",
        "HTML Form",
        "DOM",
        "DOM TREE",
        "TABLES",
        "JavaScript",
        "EVENTS",
        "Asynchronous Java Script",
        "Data Types in Java Script",
        "REGEX",
        "Loops",
        "Arrays",
        "React.js",
        "Bootstrap",
        "Python",
        "Git And GitHub",
        "Flask",
        "MySQL",
      ],
      registerLink: "https://rzp.io/rzp/7bVgfUe",
      originalPrice: "16,000",
      price: "8,000 ",
      projectCode: "LW-PSI-SP-100"
    },
    {
      title: "5. MERN STACK DEVELOPMENT",
      description: "Develop Serverless Cloud Computing Using Container for Cloud-Native Applications to simplify development, deployment & management",
      image: {
        src: "/assets/Projects/Projects/MERN.png",
        alt: "Cloud Computing Project",
        width: 400,
        height: 400,
        className: "rounded-[32px] h-auto w-auto object-contain",
        priority: true,
      },
      content: [
        "Web Development Concepts",
        "HTML",
        "CSS",
        "JavaScript",
        "MACHINE LEARNING-AI",
        "React JS",
        "Node JS",
        "Express JS",
        "MongoDB",
        "Hooks",
        "Document Object Model (DOM)",
        "Routing and APIs",
        "Asynchronous Programming",
        "Building RESTful APIs",
        "Fetching Data from API",
        "Handling Forms and User Input",
        "MERN STACK DEVELOPMENT",
        "Code Organization and Structure",
        "Error Handling"
      ],
      registerLink: "https://rzp.io/rzp/iADTiZcf ",
      originalPrice: "16,000",
      price: "8,000",
      projectCode: "LW-PSI-SP-100"
    }
  ]
};